version: '3'
services:
  redis-docker-service:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: express-app
    depends_on:
      - redis-docker-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
